---
title: "DBH_visualization"
output: html_document
---

prepare data
```{r}
DBHdata = read.csv("datasets/all_plots.csv")
DBHdata[DBHdata$Large == "", "Tree.Number"]
DBHdata[DBHdata$Tree.Number == "", ]
DBHdata = DBHdata[DBHdata$Tree.Number != "", ]
DBHdata[DBHdata$Large == "", "Large"] = "No"

T1data = DBHdata[DBHdata$Treatment == "T1: Gap", ]
T2data = DBHdata[DBHdata$Treatment == "T2: Radial", ]
Controldata = DBHdata[DBHdata$Treatment == "Control", ]
```

DBH in year0 VS year6 for T1, T2, Control
```{r}
boxplot(DBHdata$DBH.year.0~DBHdata$Treatment, boxwex = 0.3, at = c(1, 2, 3), xlab = "treatment", ylab = "DBH in year0 VS year6")
boxplot(DBHdata$DBH.year.6~DBHdata$Treatment, boxwex = 0.3, add = TRUE, at = c(1.3, 2.3, 3.3), xaxt = "n")
```

change in DBH for T1, T2, Control
```{r}
boxplot(DBHdata$DBH.year.6-DBHdata$DBH.year.0~DBHdata$Treatment, xlab = "treatment", ylab = "DBHyear6 - DBHyear0")
boxplot(DBHdata$DBH.year.6-DBHdata$DBH.year.0~DBHdata$Treatment, xlab = "treatment", ylab = "DBHyear6 - DBHyear0 (zoom in)", ylim = c(-3, 8))
```

large trees VS other trees for T1, T2, Control
```{r}
boxplot(T1data$DBH.year.6~T1data$Large, boxwex = 0.3, at = c(1.3, 2.3), xlab = "T1: Gap Large", ylab = "DBH in year0 VS year6", ylim = c(15, 70))
boxplot(T1data$DBH.year.0~T1data$Large, add = TRUE, at = c(1, 2), boxwex = 0.3)

boxplot(T2data$DBH.year.6~T2data$Large, boxwex = 0.3, at = c(1.3, 2.3), xlab = "T2: Radial Large", ylab = "DBH in year0 VS year6")
boxplot(T2data$DBH.year.0~T2data$Large, add = TRUE, at = c(1, 2), boxwex = 0.3)

boxplot(Controldata$DBH.year.6~Controldata$Large, boxwex = 0.3, at = c(1.3, 2.3), xlab = "Control treatment Large", ylab = "DBH in year0 VS year6")
boxplot(Controldata$DBH.year.0~Controldata$Large, add = TRUE, at = c(1, 2), boxwex = 0.3)
```

change in DBH large trees VS other trees for T1, T2, Control
```{r}
boxplot(T1data$DBH.year.6-T1data$DBH.year.0~T1data$Large, xlab = "Large in treatment", ylab = "DBHyear6 - DBHyear0 (zoom in)", ylim = c(-3, 8), col = "light blue", at = c(0.5, 1), boxwex = 0.5, xlim = c(0, 5))
boxplot(T2data$DBH.year.6-T2data$DBH.year.0~T2data$Large, ylim = c(-3, 8), col = "pink", at = c(2, 2.5), boxwex = 0.5, add = TRUE)
boxplot(Controldata$DBH.year.6-Controldata$DBH.year.0~Controldata$Large, ylim = c(-3, 8), at = c(3.5, 4), boxwex = 0.5, add = TRUE)
legend("topright", legend = c("T1: Gap", "T2: Radial", "Control"), fill = c("light blue", "pink", "grey"))
```

boxplot DBH in year0 VS year6 for different plot in T1, T2, Control
```{r}
boxplot(T1data$DBH.year.0~T1data$Plot, at = c(1, 3, 5, 7), boxwex = 0.5, xlab = "T1: Gap plot number", ylab = "DBH in year0 VS year6", ylim = c(15, 65))
boxplot(T1data$DBH.year.6~T1data$Plot, add = TRUE, at = c(1.5, 3.5, 5.5, 7.5), boxwex = 0.5, xaxt = "n")

boxplot(T2data$DBH.year.0~T2data$Plot, at = c(1, 3, 5, 7), boxwex = 0.5, xlab = "T2: Radial plot number", ylab = "DBH in year0 VS year6", ylim = c(15, 65))
boxplot(T2data$DBH.year.6~T2data$Plot, add = TRUE, at = c(1.5, 3.5, 5.5, 7.5), boxwex = 0.5, xaxt = "n")

boxplot(Controldata$DBH.year.0~Controldata$Plot, at = c(1, 3, 5, 7), boxwex = 0.5, xlab = "Control treatment plot number", ylab = "DBH in year0 VS year6", ylim = c(15, 65))
boxplot(Controldata$DBH.year.6~Controldata$Plot, add = TRUE, at = c(1.5, 3.5, 5.5, 7.5), boxwex = 0.5, xaxt = "n")
```

```{r}
boxplot(T1data$DBH.year.6-T1data$DBH.year.0~T1data$Plot, xlab = "T1: Gap plot number", ylab = "DBHyear6 - DBHyear0 (zoom in)", ylim = c(-3, 8), xlim = c(0, 8), at = c(0.5, 1, 1.5, 2), boxwex = 0.45, col = "light blue")

boxplot(T2data$DBH.year.6-T2data$DBH.year.0~T2data$Plot, ylim = c(-3, 8), at = c(3, 3.5, 4, 4.5), boxwex = 0.45, add = TRUE, col = "pink")

boxplot(Controldata$DBH.year.6-Controldata$DBH.year.0~Controldata$Plot, ylim = c(-3, 8), at = c(6, 6.5, 7, 7.5), boxwex = 0.45, add = TRUE)
legend("topright", legend = c("T1: Gap", "T2: Radial", "Control"), fill = c("light blue", "pink", "grey"))
```