---
title: "DSproj"
output:
  pdf_document: default
  html_document: default
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(readxl)
library(tidyr)
library(dplyr)
library(lme4)
```

## Prep
```{r}
diversity_df <- read.csv('../dataset/tables/species_divers_quadrats.csv')
diversity_df_plot <- read.csv('../contingency tables/output/diversity/species_divers_plots.csv')
diversity_df_treat <- read.csv('../contingency tables/output/diversity/species_divers_treatments.csv')
```

## Hypothesis 1
#### There will be a greater increase in understorey species diversity in T1 as compared to T2, and in T2 compared to Control plots (diversity is a measure of both abundance and richness)              

### Year 0 vs Year 6
```{r}
diversity_df %>% drop_na(X0, X6) 
diversity_df$Increase_0to6 <- diversity_df$X6 > diversity_df$X0
diversity_df$Increase_0to6 <- as.numeric(diversity_df$Increase_0to6)

str(diversity_df)
```
Model 1 - Treatment + Gap + Fenced + Gap*Fenced
```{r}
hyp1_div_mod1 <- glm(Increase_0to6 ~ Treatment + Gap + Fenced + Gap*Fenced,
                          family='binomial', data=diversity_df)
summary(hyp1_div_mod1)
```

```{r}
hyp1_div_mod1 <- glm(Increase_0to6 ~ Treatment + Gap + Fenced + Gap*Fenced,
                          family='poisson', data=diversity_df)
summary(hyp1_div_mod1)
```

```{r}
hyp1_div_mod2 <- glm(Increase_0to6 ~ 1 + Gap*Fenced + Treatment*Fenced + Treatment*Gap,
                          family='binomial', data=diversity_df)
summary(hyp1_div_mod2)
```

Model 3 - Mixed effect 
```{r}
hyp1_div_mod3 <- lmer(Increase_0to6 ~ 1 + Treatment + Fenced + Gap + (1|Treatment) + (1|Fenced) + (1|Gap),
                          data=diversity_df)
summary(hyp1_div_mod3)
```