---
title: "DSproj"
output:
  pdf_document: default
  html_document: default
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(readxl)
```

```{r}
df <- read.csv("../preprocessed data/understoreydata2020.csv", header = TRUE)
#df <- read_excel("../datasets/Ecothining_understoreydata2020.xlsx", col_names = TRUE)
head(df)
```

```{r}
unique(df$Plot_number)
df$Group <- 0

for (i in 1:nrow(df)) {
  if (df[i,5] %in% c(1, 8, 10, 12)) {
    df[i,]$Group <- "t1"
  } else if (df[i,5] %in% c(3,5,7,9)) {
    df[i,]$Group <- "t2"
  } else if (df[i,5] %in% c(2,4,6,11)){
    df[i,]$Group <- "control"
  }
}

#df$Group
```

```{r}
t1 <- df[df$Plot_number %in% c(1,8,10,12),]
t2 <- df[df$Plot_number %in% c(3,5,7,9),]
control <- df[df$Plot_number %in% c(2,4,6,11),]

grp_col <- rep(c("t1", "t2", "control"), each=length(unique(t1$Quadrat_number)))
quadrat_col <- rep(c(1:32), 3)
summary_df <- data.frame(Grp = grp_col, Quadrat_num = quadrat_col)
summary_df$Fenced <- FALSE
summary_df$Species_num <- 0

# T1
t1_summary <- t1[!duplicated(t1[,c("Year_monitoring","Plot_number","Quadrat_number")]),]
t1_summary <- t1_summary[c("Year_monitoring","Plot_number","Quadrat_number", "Quadrat_fenced")]
t1_summary$Species_num <- 0
for (i in 1:nrow(t1_summary)) {
  t1_summary[i,]$Species_num <- nrow(subset(t1,Quadrat_number==t1_summary[i,]$Quadrat_number & 
                                              Plot_number==t1_summary[i,]$Plot_number &
                                              Year_monitoring==t1_summary[i,]$Year_monitoring))
}

# T2
t2_summary <- t2[!duplicated(t2[,c("Year_monitoring","Plot_number","Quadrat_number")]),]
t2_summary <- t2_summary[c("Year_monitoring","Plot_number","Quadrat_number", "Quadrat_fenced")]
t2_summary$Species_num <- 0
for (i in 1:nrow(t2_summary)) {
  t2_summary[i,]$Species_num <- nrow(subset(t2,Quadrat_number==t2_summary[i,]$Quadrat_number & 
                                              Plot_number==t2_summary[i,]$Plot_number &
                                              Year_monitoring==t2_summary[i,]$Year_monitoring))
}

# Control
ctl_summary <- control[!duplicated(control[,c("Year_monitoring","Plot_number","Quadrat_number")]),]
ctl_summary <- ctl_summary[c("Year_monitoring","Plot_number","Quadrat_number", "Quadrat_fenced")]
ctl_summary$Species_num <- 0
for (i in 1:nrow(ctl_summary)) {
  ctl_summary[i,]$Species_num <- nrow(subset(control,Quadrat_number==ctl_summary[i,]$Quadrat_number & 
                                              Plot_number==ctl_summary[i,]$Plot_number &
                                              Year_monitoring==ctl_summary[i,]$Year_monitoring))
}
```

## Calculate Shannon Diversity Index
Per group per plot
```{r}
calc_sdi <- function(df) {
  plots <- unique(df$Plot_number)
  res <- data.frame(PlotNum=plots, Year=rep(c(0,3,6), each=length(plots)), SDI=rep(c(0,0,0), each=length(plots)))
  for (p in plots) {
    for (i in c(0, 3, 6)) {
      total_count <- nrow(subset(df, Year_monitoring==i, Plot_number==p))
      yr_subset <- df[df$Year_monitoring==i & df$Plot_number==p,]
      yr_unique_species <- yr_subset[!duplicated(yr_subset[,c("T002_Flora_Species_name")]),]
      sdi <- 0
      for (j in 1:nrow(yr_unique_species)) {
        species_count <- nrow(subset(yr_subset, T002_Flora_Species_name==yr_unique_species[j,]$T002_Flora_Species_name))
        species_prop <- species_count / total_count
        sdi <- sdi + (species_prop * log(species_prop))
      }
      res$SDI[res$Year==i & res$PlotNum==p] <- -1 * sdi
    }
  }
  print(res)
}

t1_sdi <- calc_sdi(t1)
t2_sdi <- calc_sdi(t2)
ctl_sdi <- calc_sdi(control)
```


## Hypothesis  
#### There will be a greater increase in understorey species diversity in T1 as compared to T2, and in T2 compared to Control plots (diversity is a measure of both abundance and richness)
```{r}

```